---
- name: RHEL Dev Workstation Post Install Configuration
  hosts: all
  become: true
  tasks:
    - name: Activate RHEL machine with subscription manager using an activationkey
      ansible.builtin.command: subscription-manager register --org 11009103 --activationkey pleathen-rhel --force
    - name: Activate vscode repo using rpm
      ansible.builtin.command: rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Create repo file /etc/yum.repos.d/vscode.repo
      ansible.builtin.file:
        path: /etc/yum.repos.d/vscode.repo
        state: touch
    - name: Add the following to the vscode.repo file
      ansible.builtin.blockinfile:
        path: /etc/yum.repos.d/vscode.repo
        block: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
    - name: Add vscode repo
      ansible.builtin.command: sudo dnf check-update
