---
- name: RHEL Dev Workstation Post Install Configuration
  hosts: all
  become: true
  tasks:
    - name: Activate subscription
      ansible.builtin.command: sudo subscription-manager register --org --activationkey <activation_key>
    - name: Activate VSCode repos
      ansible.builtin.command: sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    - name: Create repo file
      ansible.builtin.command: sudo vi /etc/yum.repos.d/vscode.repo
