---
- name: Register a RHEL 9 VM and attach a subscription
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Register a RHEL 9 VM and attach a subscription
      community.general.redhat_subscription:
        state: present
        username: "{{ lookup('env', 'REDHAT_USERNAME') }}"
        password: "{{ _password_ }}"
        auto_attach: true
        pool_ids: "{{ lookup('env', 'REDHAT_POOL_ID') }}"
        server_hostname: "{{ lookup('env', 'RHEL_HOSTNAME') }}"
        server_insecure: "{{ _server_insecure_ }}"
        rhsm_baseurl: "{{ lookup('env', 'RHEL_BASE_URL') }}"
        server_proxy_hostname: "{{ lookup('env', 'RHEL_PROXY_HOSTNAME') }}"
        server_proxy_port: "{{ lookup('env', 'RHEL_PROXY_PORT') }}"
        server_proxy_user: "{{ lookup('env', 'RHEL_PROXY_USER') }}"
        server_proxy_password: "{{ _server_proxy_password_ }}"
