---
- name: Setup Developer Workstation
  hosts: dev_workstations
  become: true

  tasks:
    - name: Ensure the system is up to date
      ansible.builtin.dnf:
        name: '*'
        state: present

    - name: Install common development tools
      ansible.builtin.dnf:
        name:
          - git
          - vim
          - docker
          - gcc
          - make
        state: present

    - name: Import Microsoft GPG key
      ansible.builtin.rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add VSCode repository
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgcheck: true
        enabled: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: Install Visual Studio Code
      ansible.builtin.dnf:
        name: code
        state: present

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ user_name }}"
        groups: docker
        append: true

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Set up global Git configuration
      community.general.git_config:
        name: user.name
        value: "Developer Name"
        scope: global

    - name: Copy custom Vim configuration
      ansible.builtin.copy:
        src: /path/to/your/.vimrc
        dest: /home/{{ user_name }}/.vimrc
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Ensure SELinux is enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

  vars:
    user_name: developer  # Replace with the actual username
